apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmarcts.fullname" . }}
  labels:
    {{- include "dmarcts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.serviceMonitor.enabled }}
    - port: {{ .Values.prometheusScraping.port }}
      targetport: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "dmarcts.selectorLabels" . | nindent 4 }}
